### ISSUE TITLE
bin2hex crashes with input length >= 1e7

### ISSUE THREAD

**Issue by dirkschumacher** [jeroen/sodium#19]
`bin2hex` crashes my R (4.0.2) session on a mac when the input is too long it seems:

`res <- bin2hex(raw(1e7))` crashes without a message.

**Comment by jedisct1** [comment]
Hi!

In libsodium, `bin2hex` expects binary data, that can be arbitrarily long, not an integer.

Maybe the R bindings try convert integers to some binary representation first, but this is something very specific to their code, that doesn't exist here.

The best thing to do would be to open an issue in their repository. Unfortunately, there's not much that can be done in libsodium itself.

**Comment by jedisct1** [comment]
Aahahah scratch that, I though it was an issue posted in the libsodium issue tracker.

Need more sleep :)

**Comment by dirkschumacher** [comment]
Hehe, no worries :)

**Comment by dirkschumacher** [comment]
This line fails it seems:
https://github.com/jeroen/sodium/blob/127465865ba7c6fded44a0d4c0a738fb1360f3f7/src/helpers.c#L12

**Comment by jeroen** [comment]
Thanks, should be fixed now. Apparently there is a limit to the size of an array on the stack. Fixed my switching to malloc.

**Comment by dirkschumacher** [comment]
Oh great. Thanks a lot! Interesting, did not know regarding the stack limit.
